import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Container(
            width: 311,
            height: 80,
            child: Stack(
              children: [
                Container(
                  width: 311,
                  height: 80,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE2F1FB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0xCCFFFFFF),
                        blurRadius: 20,
                        offset: Offset(-8, -8),
                        spreadRadius: 0,
                      ),
                      BoxShadow(
                        color: Color(0x665FCCEC),
                        blurRadius: 20,
                        offset: Offset(8, 8),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
                Container(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: [
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 24),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.end,
                          children: [
                            Text(
                              '1Month',
                              style: TextStyle(
                                color: Color(0xFF2D4450),
                                fontSize: 18,
                                fontFamily: 'Helvetica Neue',
                                fontWeight: FontWeight.w700,
                                height: 0.06,
                              ),
                            ),
                            const SizedBox(width: 125),
                            Container(
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.end,
                                crossAxisAlignment: CrossAxisAlignment.end,
                                children: [
                                  Text(
                                    '\$',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF2D4450),
                                      fontSize: 16,
                                      fontFamily: 'Helvetica Neue',
                                      fontWeight: FontWeight.w400,
                                      height: 0.08,
                                    ),
                                  ),
                                  const SizedBox(width: 2),
                                  Text(
                                    '11.49',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF2D4450),
                                      fontSize: 24,
                                      fontFamily: 'Helvetica Neue',
                                      fontWeight: FontWeight.w700,
                                      height: 0.04,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 4),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 24),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              '3-Day Trial',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF85A7B4),
                                fontSize: 16,
                                fontFamily: 'Helvetica Neue',
                                fontWeight: FontWeight.w400,
                                height: 0.08,
                              ),
                            ),
                            const SizedBox(width: 110),
                            Text(
                              'per month',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF85A7B4),
                                fontSize: 16,
                                fontFamily: 'Helvetica Neue',
                                fontWeight: FontWeight.w400,
                                height: 0.08,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ]),
      ),
    );
  }
}
