# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: deploy

on:
  push:
    branches:
      - release
      - adhoc
  pull_request:
    branches:
      - release
      - adhoc
jobs:
  build_default:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install CocoaPods and Fastlane
      run: |
        # gem install cocoapods
        gem install fastlane -NV

    - name: Install Apple certificates
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-filepath: ios/fastlane/Certificates11.p12
        # p12-file-base64: ${{ secrets.CERTIFICATE_P12 }}
        # p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
        p12-password: 2222

    - name: Install and set Flutter version
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'
        channel: 'stable'
        architecture: x64

    - name: Flutter pub get
      run: |
         flutter pub get
         cd ios
         pod install
         cd ..

  build_adhoc:
    needs: build_default
    runs-on: macos-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/adhoc'  # 添加条件判断，只有在 adhoc 分支上推送时执行

    steps:
    - uses: actions/checkout@v3

    - name: Install Apple certificates
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-filepath: ios/fastlane/Certificates11.p12
        # p12-file-base64: ${{ secrets.CERTIFICATE_P12 }}
        # p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
        p12-password: 2222

    - name: Code signing settings
      run: |
        cd ios
        fastlane code_signing_settings_adhoc
        cd ..

    - name: Package adhoc
      # env:
      #   # FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }} # 设置环境变量
      #   # APPLE_ID: ${{ secrets.APPLE_ID }}
      #   # TEAM_ID: ${{ secrets.TEAM_ID }} # 您的Apple开发者团队ID
      #   # APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      #   # FASTLANE_PASSWORD: 2222
      run: |
        cd ios
        fastlane adhoc
        cd ..

      # run: |
      #   cd ios
      #   # fastlane action app_store_connect_api_key
      #   fastlane release
      #   # fastlane match_all
      #   cd ..

    # - name: upload testflight1
    #   run: fastlane release

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        # echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        cp -r ios/fastlane/id_rsa ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: Push to Web Repository
      run: |
        pwd

        # Configure git
        git config --global user.email "sunlightjustin@icloud.com"
        git config --global user.name "SunlightJustin"

        # Clone another repository
        # git clone https://github.com/SunlightJustin/SunlightJustin.github.io.git
        git clone git@github.com:SunlightJustin/SunlightJustin.github.io.git
        
        # Copy build artifacts or other files
        cp -r ios/uat/Runner.ipa SunlightJustin.github.io

        # Commit and push to another repository
        cd SunlightJustin.github.io
        git add .
        git commit -m "Update from GitHub Actions"
        git push origin main

  build_release:
    needs: build_default
    runs-on: macos-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/release'  # 添加条件判断，只有在 adhoc 分支上推送时执行

    steps:
    - uses: actions/checkout@v3

    - name: Code signing settings
      run: |
        cd ios
        fastlane code_signing_settings_app_store
        cd ..

    - name: Upload testflight
      run: |
        cd ios
        fastlane release
        cd ..

